-d C:\Users\1kfil\Documents\C\FPGA_Tetris\hdmi_test\impl\gwsynthesis\hdmi_test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\1kfil\Documents\C\FPGA_Tetris\hdmi_test\tangnano9k.cst
-cfg C:\Users\1kfil\Documents\C\FPGA_Tetris\hdmi_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
